on: push
name: terraform_ci-cd
run-name: ubuntu-latest
jobs:
  dev:
    name: init
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false
      - name: command line
        run: |
          ls -ltr
          terraform init
          terraform plan -var-file variables.tfvars --out=tfplan.out 
          terraform apply tfplan.out
  test:
    name: init
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false
      - name: command line
        run: |
          ls -ltr
          terraform init
          terraform plan -var-file variables-test.tfvars --out=tfplan.out